name: Paper Recommendation Pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  recommend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          activate-environment: true
          enable-cache: true
          cache-suffix: "paper-digest-action"
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: |
          uv sync
          if [ "${{ steps.setup-uv.outputs.cache-hit }}" == 'true' ]; then
            echo "Cache was restored, using cached dependencies"
          else
            echo "No cache found, installing dependencies from scratch"
          fi

      # - name: Cache data directory
      #   id: cache-data
      #   uses: actions/cache@v3
      #   with:
      #     path: ./cache
      #     key: paper-digest-huggingface

      # - name: Check cache status
      #   run: |
      #     if [ "${{ steps.cache-data.outputs.cache-hit }}" == 'true' ]; then
      #       echo "数据缓存命中，使用缓存的数据"
      #     else
      #       echo "未找到数据缓存，将在运行过程中创建新的缓存"
      #     fi
        
      - name: Run recommendation script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          DOUBAO_API_KEY: ${{ secrets.DOUBAO_API_KEY }}
        run: python script/recommend.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push summarized data
        run: |
          if git diff --quiet summarized/; then
            echo "No changes to summarized data. Skipping commit."
          else
            git add summarized/
            git commit -m "Update summarized data [skip ci]"
            git push
          fi


