name: Paper Recommendation Pipeline

on:
  workflow_dispatch:

jobs:
  recommend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          activate-environment: true
          enable-cache: true
          cache-suffix: "paper-digest-action"
          cache-dependency-glob: "**/pyproject.toml|**/uv.lock"

      - name: Install dependencies
        run: |
          uv sync
          if [ "${{ steps.setup-uv.outputs.cache-hit }}" == 'true' ]; then
            echo "Cache was restored, using cached dependencies"
          else
            echo "No cache found, installing dependencies from scratch"
          fi

      - name: Cache data directory
        id: cache-data
        uses: actions/cache@v3
        with:
          path: ./cache
          key: paper-digest-huggingface

      - name: Check cache status
        run: |
          if [ "${{ steps.cache-data.outputs.cache-hit }}" == 'true' ]; then
            echo "数据缓存命中，使用缓存的数据"
          else
            echo "未找到数据缓存，将在运行过程中创建新的缓存"
          fi

      - name: 将所有 secrets 设置为环境变量
        run: |
          # 将 secrets 导出为环境变量
          echo "${{ toJson(secrets) }}" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
        shell: bash
        
      - name: Run recommendation script
        run: python script/recommend.py

      - name: Upload recommendations
        uses: actions/upload-artifact@v4
        with:
          name: summarized
          path: summarized.parquet
          retention-days: 60


